updated to use sdk instead of direct api calls
watson-developer-cloud/doc-tutorial-downloads pull request #164
Opened 2021-07-27 17:45 UTC by AndresJaramillo9

Added steps for using the Python SDK instead of making direct API calls. Also updated and added some more instructions that are more user friendly to read.

2021-07-27 19:12 UTC, evaline-ju commented on natural-language-understanding/custom_classifications_example.ipynb
> +    "## 5. How to Use a Trained Classifcation Model for Analysis\n",
spelling

2021-07-27 19:19 UTC, kmacdonald06 approved these changes
Everything seems right

2021-07-27 19:20 UTC, kmacdonald06 commented on natural-language-understanding/custom_classifications_example.ipynb
> +    "## 5. How to Use a Trained Classifcation Model for Analysis\n",
Fixed - thanks

2021-07-27 20:58 UTC, AndresJaramillo9 commented
Accidentally committed with my API key information exposed, the file has been updated and that key is no longer active.

2021-07-27 23:16 UTC, gkumbhat requested changes

2021-07-27 23:16 UTC, gkumbhat commented on natural-language-understanding/custom_classifications_example.ipynb
> +    "## 3. How to Train a NLU Classifications Model\n",
Are we removing the `Fetch data from NLC` section? We need this section actually in the notebook to be able to give customers an option to get their data from NLC.

2021-07-29 13:09 UTC, kmacdonald06 approved these changes
lgtm

2021-07-30 04:55 UTC, gkumbhat commented on natural-language-understanding/custom_classifications_example.ipynb
> +    "model_to_delete = nlu.delete_classifications_model(model_id=model_id)\n",
nit: would it make sense to rename this variable from `model_to_delete` to `deleted_model` ?

2021-07-30 04:58 UTC, gkumbhat approved these changes
Left a small nit. But otherwise looks good to me. thanks for updating the notebook.

2021-07-30 14:14 UTC, mediumTaj commented
@kmacdonald06 Can you mere this if it looks good to you? We don't have merge permissions

2021-07-30 14:16 UTC, merged